name: Tests

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]
        laravel: ["^10.0", "^11.0"]
        stability: ["prefer-stable", "prefer-lowest"]
        exclude:
          - laravel: "^11.0"
            php: "8.1"
    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Setup Problem Matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install composer dependencies
        run: |
          composer require "illuminate/collections:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Run tests
        run: php vendor/bin/phpunit --testdox

      - name: Run PHPStan
        run: php vendor/bin/phpstan --error-format=github
